IP        = "169.254.45.81"
bitfile   = "dss_2in_2048ch_983mhz_real.fpg"
adc_bits  = 16
program   = false

[snapshots]
snap_names = ["adc_snapshot0", "adc_snapshot1"]
n_samples  = 256

[spectra]
bram_names = [["a2_0", "a2_1", "a2_2", "a2_3"], 
              ["b2_0", "b2_1", "b2_2", "b2_3"]]
addr_width = 9
data_width = 64
bandwidth  = 983.04 # MHz
reset_reg  = "cnt_rst"
acc_reg    = "acc_len"
acc_len    = 1000
dBFS       = 86

[dss]
corr_brams  = [["ab_re0", "ab_re1", "ab_re2", "ab_re3"], 
               ["ab_im0", "ab_im1", "ab_im2", "ab_im3"]]
synth_brams = [["synth0_0", "synth0_1", "synth0_2", "synth0_3"], 
               ["synth1_0", "synth1_1", "synth1_2", "synth1_3"]]
const_brams = [[["bram_mult0_0_bram_re", "bram_mult0_1_bram_re",
                 "bram_mult0_2_bram_re", "bram_mult0_3_bram_re"],
                ["bram_mult0_0_bram_im", "bram_mult0_1_bram_im", 
                 "bram_mult0_2_bram_im", "bram_mult0_3_bram_im"]],
               [["bram_mult1_0_bram_re", "bram_mult1_1_bram_re", 
                 "bram_mult1_2_bram_re", "bram_mult1_3_bram_re"],
                ["bram_mult1_0_bram_im", "bram_mult1_1_bram_im", 
                 "bram_mult1_2_bram_im", "bram_mult1_3_bram_im"]]]
const_nbits = 32
const_binpt = 27

[experiment]
lo_freq      = 3 # GHz
rf_power     = -25 # dBm
bin_step     = 16
cal_datadir  = "dss_cal"
srr_datadir  = "dss_srr"
pause_time   = 0.5 # should be > (1/bandwidth * FFT_size * acc_len * 2) in
                   # order for the spectra to be fully computed after a
                   # tone change
load_consts  = true
load_ideal   = false
cal_tar      = "dss_cal.tar.gz"
rf_generator = "TCPIP::169.254.99.253::INSTR"
